CREATE TABLE `Page` (
    `page_id` INT AUTO_INCREMENT NOT NULL, `title` VARCHAR(255) NOT NULL, `url` VARCHAR(2083) NOT NULL, `summary` TEXT NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `state` TINYINT NOT NULL DEFAULT 1, PRIMARY KEY (`page_id`)
);

CREATE TABLE `User` (
    `user_id` INT AUTO_INCREMENT NOT NULL, `auth_id` BIGINT NOT NULL, `email` VARCHAR(255) NOT NULL, `user_name` VARCHAR(255) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `state` TINYINT NOT NULL DEFAULT 1, `access_token` VARCHAR(255) NULL, `token_type` VARCHAR(255) NULL, `expires_in` VARCHAR(255) NULL, `refresh_token` VARCHAR(255) NULL, `scope` VARCHAR(255) NULL, `id_token` VARCHAR(255) NULL, PRIMARY KEY (`user_id`)
);

CREATE TABLE `Bookmark` (
    `bookmark_id` INT AUTO_INCREMENT NOT NULL, `page_id` INT NOT NULL, `user_id` INT NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `state` TINYINT NOT NULL DEFAULT 1, PRIMARY KEY (`bookmark_id`), FOREIGN KEY (`page_id`) REFERENCES `Page` (`page_id`), FOREIGN KEY (`user_id`) REFERENCES `User` (`user_id`)
);

CREATE TABLE `Content` (
    `content_id` INT AUTO_INCREMENT NOT NULL, `user_id` INT NULL DEFAULT 0, `content` TEXT NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP(3), `state` TINYINT NOT NULL DEFAULT 1, PRIMARY KEY (`content_id`), FOREIGN KEY (`user_id`) REFERENCES `User` (`user_id`)
);